#!/usr/bin/python

import os
import sys
from syslog import syslog
from ec2sys_autotune.ec2_autotune_stop import Ec2AutotuneStop
from ec2sys_autotune.ec2_instance_exception import Ec2AutotuneError
import argparse


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--config',
                        default="/etc/ec2sys-autotune.cfg",
                        help='Configuration file to use',
                        type=str)

    args = parser.parse_args()
    autotune = Ec2AutotuneStop(args.config)
    try:
        autotune.stop()
    except Ec2AutotuneError, e:
        syslog(e.msg)
        sys.exit(-1)
    sys.exit(0)

if __name__ == '__main__':
    main()
